services:
  db:
    image: postgres:15
    container_name: wallet_db
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./internal/db/migrations:/docker-entrypoint-initdb.d:ro
    ports:
      - "${PG_PORT}:5432"

  app:
    build: .
    container_name: wallet_app
    environment:
      PORT: ${PORT}
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB: ${PG_DB}
      PG_SSLMODE: ${PG_SSLMODE}
    depends_on:
      - db
    ports:
      - "${PORT}:8080"
    restart: unless-stopped
    command: ["/wallet-app"]

volumes:
  db_data:
